CREATE DATABASE FILM_MANAGEMENT

USE FILM_MANAGEMENT;

CREATE TABLE CATEGORY (
    ID INT PRIMARY KEY,
    CAT_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT ,
    STATUS BIT NOT NULL
);

CREATE TABLE FILM (
     ID INT PRIMARY KEY,
     FILM_NAME VARCHAR(50) NOT NULL,
     CONTENT TEXT NOT NULL,
     DURATION TIME NOT NULL,
     DIRECTOR VARCHAR(50),
     RELEASE_DATE DATE NOT NULL
);

CREATE TABLE CATEGORY_FILM (
  CAT_ID INT NOT NULL,
  FILM_ID VARCHAR(50) NOT NULL
)

ALTER TABLE CATEGORY_FILM 
ADD FOREIGN KEY ( CAT_ID ) REFERENCES CATEGORY(ID);

ALTER TABLE CATEGORY_FILM
MODIFY COLUMN FILM_ID INT;

ALTER TABLE CATEGORY_FILM 
ADD FOREIGN KEY ( FILM_ID ) REFERENCES FILM(ID);

ALTER TABLE FILM
ADD COLUMN STATUS TINYINT DEFAULT(1);

ALTER TABLE CATEGORY 
DROP COLUMN STATUS

ALTER TABLE CATEGORY_FILM

DROP CONSTRAINT category_film_ibfk_2
DROP CONSTRAINT category_film_ibfk_1
