CREATE DATABASE RIKKEI_MANAGEMENT

USE RIKKEI_MANAGEMENT;

-- TAO CAC BANG

CREATE TABLE DEPARTMENTS (
   DEPARTMENT_ID INT PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL UNIQUE,
   LOCATION VARCHAR(255)
);

CREATE TABLE EMPLOYEES (
   EMPLOYEE_ID INT PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL,
   DOB DATE,
   DEPARTMENR_ID INT NOT NULL,
   SALARY DECIMAL(10,2) NOT NULL,
   FOREIGN KEY(DEPARTMENR_ID) REFERENCES DEPARTMENTS(   DEPARTMENT_ID)
);


CREATE TABLE PROJECTS (
   PROJECT_ID INT PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL,
   START_DATE DATE,
   END_DATE DATE
);

CREATE TABLE TIMESHEETS (
   TIMESHEETS_ID INT PRIMARY KEY,
   EMPLOYEE_ID INT NOT NULL,
   PROJECT_ID INT NOT NULL,
   WORK_DATE DATE,
   HOURS_WORKED DECIMAL(5,2),
   FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
   FOREIGN KEY( PROJECT_ID) REFERENCES PROJECTS( PROJECT_ID)
);

CREATE TABLE WORK_REPORT (
   REPORT_ID INT PRIMARY KEY,
   EMPLOYEE_ID INT NOT NULL,
   REPORT_DATE DATE ,
   REPORT_CONTENT TEXT,
   FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- THEM DU LIEU VAO BANG

INSERT INTO DEPARTMENTS
VALUES
(1, 'SALE','77 LE TRUNG NGHIA'),
(2, 'DAO TAO', '97 MAN THIEN')

SELECT * FROM PROJECTS

INSERT INTO EMPLOYEES
VALUES
(1, 'HO XUAN HUNG','1999/1/1', (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE NAME = 'DAO TAO'), 10000),
(2, 'NGUYEN THANH BINH PHUOC', '1999/1/1', (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE NAME ='DAO TAO'),10000)

INSERT INTO PROJECTS
VALUES
(1, 'JAVASCRIPT','2025/1/1', '2025/2/2'),
(2, 'JAVA', '2025/1/12', '2025/3/12');

INSERT INTO TIMESHEETS
VALUES
(1, 
(SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE NAME = 'HO XUAN HUNG' LIMIT 1), 
(SELECT PROJECT_ID FROM PROJECTS WHERE NAME = 'JAVA'),
'2025/2/19',
20
),
(2, 
(SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE NAME = 'NGUYEN THANH BINH PHUOC'), 
(SELECT PROJECT_ID FROM PROJECTS WHERE NAME = 'JAVASCRIPT'),
'2025/2/19',
30
)


INSERT INTO WORK_REPORT
VALUES
(1, (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE NAME = 'NGUYEN THANH BINH PHUOC'),'2025/1/1', 'Tang luongggg'),
(2, (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE NAME = 'HO XUAN HUNG'),'2025/1/1', 'Lam hoai ko het viec :(((')

UPDATE PROJECTS 
SET NAME = 'HTML-CSS'
WHERE NAME = 'JAVASCRIPT'

SELECT CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'TIMESHEETS' AND REFERENCED_TABLE_NAME = 'EMPLOYEES';


ALTER TABLE TIMESHEETS
DROP FOREIGN KEY timesheets_ibfk_5;



ALTER TABLE TIMESHEETS
ADD FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE;

DELETE FROM EMPLOYEES 
WHERE NAME = 'HO XUAN HUNG'


